version: '3.8'

services:
  rasa:
    image: rasa/rasa:3.6.13-full
    ports:
      - "5005:5005"
    volumes:
      - ./app/rasa:/app
    working_dir: /app
    command: >
      bash -c "rasa train --domain domain.yml --data data/ --config config.yml &&
               rasa run --enable-api --cors '*' --debug --port 5005"
    environment:
      - RASA_TELEMETRY_ENABLED=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
